export const GET_SIDE_DETAIL = 'GET_SIDE_DETAIL'
export const GET_SPELL_DETAIL = 'GET_SPELL_DETAIL'
export const GET_FONT_ID = 'GET_FONT_ID'
export const HIDE_LIST = 'HIDE_LIST'
export const SHOW_LIST = 'SHOW_LIST'
export const ADD_HISTORY = 'ADD_HISTORY'
